import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from '@rsbuild/core';
import type { RsbuildPlugin } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';
import sharp from 'sharp';

interface PhotoPreviewEntry {
  originalUrl: string;
  previewDataUrl: string;
}

const PROJECT_ROOT = dirname(fileURLToPath(import.meta.url));
const PERSONAL_CONSTANT_PATH = join(PROJECT_ROOT, 'src/pages/personal/constant.ts');
const PHOTO_PREVIEWS_MODULE_PATH = join(PROJECT_ROOT, 'src/pages/personal/photoPreviews.generated.ts');
const PREVIEW_BATCH_SIZE = 4;

// 从个人页图片常量中提取启用的远程图片 URL，注释掉的图片不会参与构建期预览图生成。
const extractAircraftPhotoUrls = (constantSource: string): string[] => {
  const imgsDeclarationMatch = constantSource.match(/export const imgs: string\[\] = \[([\s\S]*?)\];/);

  if (!imgsDeclarationMatch) {
    return [];
  }

  const uncommentedImgsSource = imgsDeclarationMatch[1]
    .split('\n')
    .filter((line: string): boolean => !line.trim().startsWith('//'))
    .join('\n');
  const photoUrlMatches = uncommentedImgsSource.matchAll(/'((?:https?:\/\/)[^']+)'/g);

  return Array.from(new Set(Array.from(photoUrlMatches, (photoUrlMatch: RegExpMatchArray): string => photoUrlMatch[1])));
};

// 将远程原图压缩成极小 WebP data URL，供列表缩略图首屏展示。
const createPhotoPreviewDataUrl = async (photoUrl: string): Promise<string | null> => {
  try {
    const imageResponse = await fetch(photoUrl);

    if (!imageResponse.ok) {
      console.warn(`[photo-preview] 图片下载失败：${photoUrl}`);
      return null;
    }

    const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());
    const previewBuffer = await sharp(imageBuffer)
      .rotate()
      .resize({ width: 48, height: 48, fit: 'cover' })
      .webp({ quality: 28, effort: 4 })
      .toBuffer();

    return `data:image/webp;base64,${previewBuffer.toString('base64')}`;
  } catch {
    console.warn(`[photo-preview] 图片预览图生成失败：${photoUrl}`);
    return null;
  }
};

// 分批处理远程图片，避免构建时同时发起过多下载请求。
const createPhotoPreviewEntries = async (photoUrls: string[]): Promise<PhotoPreviewEntry[]> => {
  const photoPreviewEntries: PhotoPreviewEntry[] = [];

  for (let startIndex = 0; startIndex < photoUrls.length; startIndex += PREVIEW_BATCH_SIZE) {
    const photoUrlBatch = photoUrls.slice(startIndex, startIndex + PREVIEW_BATCH_SIZE);
    const batchEntries = await Promise.all(
      photoUrlBatch.map(async (photoUrl: string): Promise<PhotoPreviewEntry | null> => {
        const previewDataUrl = await createPhotoPreviewDataUrl(photoUrl);

        return previewDataUrl ? { originalUrl: photoUrl, previewDataUrl } : null;
      }),
    );

    batchEntries.forEach((photoPreviewEntry: PhotoPreviewEntry | null): void => {
      if (photoPreviewEntry) {
        photoPreviewEntries.push(photoPreviewEntry);
      }
    });
  }

  return photoPreviewEntries;
};

// 生成一个可被页面常量读取的 TS 模块；开发模式没有执行插件时会使用仓库内的空映射兜底。
const writePhotoPreviewsModule = async (photoPreviewEntries: PhotoPreviewEntry[]): Promise<void> => {
  const previewRecordEntries = photoPreviewEntries
    .map(
      (photoPreviewEntry: PhotoPreviewEntry): string =>
        `  ${JSON.stringify(photoPreviewEntry.originalUrl)}: ${JSON.stringify(photoPreviewEntry.previewDataUrl)},`,
    )
    .join('\n');
  const moduleSource = [
    '// This file is generated by rsbuild.config.ts during production build.',
    '// Do not edit by hand.',
    'export const aircraftPhotoPreviewUrls = {',
    previewRecordEntries,
    '} satisfies Record<string, string>;',
    '',
  ].join('\n');

  await writeFile(PHOTO_PREVIEWS_MODULE_PATH, moduleSource);
};

const pluginAircraftPhotoPreviews = (): RsbuildPlugin => ({
  name: 'plugin-aircraft-photo-previews',
  setup(api): void {
    api.onBeforeBuild(async (): Promise<void> => {
      const constantSource = await readFile(PERSONAL_CONSTANT_PATH, 'utf8');
      const photoUrls = extractAircraftPhotoUrls(constantSource);
      const photoPreviewEntries = await createPhotoPreviewEntries(photoUrls);

      await writePhotoPreviewsModule(photoPreviewEntries);
    });
  },
});

// Docs: https://rsbuild.rs/config/
export default defineConfig({
  html: {
    favicon: 'https://avatars.githubusercontent.com/u/32100575?v=4',
    title: 'Plan List | 航司机型资料库',
    meta: {
      author: 'Plan List',
      description: 'Plan List 是面向航空爱好者的航司机型资料库与个人乘坐记录工具。',
      keywords: '航司机型,飞机型号,航空资料库,乘坐记录,Plan List',
      'theme-color': '#07111d',
      viewport: 'width=device-width, initial-scale=1.0',
    },
  },
  plugins: [pluginReact(), pluginAircraftPhotoPreviews()],
});
