// This file is generated by pluginSketchfabFileSizeGuard during the production build.
// Do not edit by hand.
export const uploadOssGlbAssets = [
    { sourcePath: "sketchfab/boeing_727.glb", fileName: "boeing_727.glb" },
] as const;
