import { mkdir, readdir, rename, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import type { RsbuildPlugin } from "@rsbuild/core";

const PLUGIN_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(PLUGIN_DIRECTORY, "..");
const SKETCHFAB_DIRECTORY = join(PROJECT_ROOT, "public/models/sketchfab");
const UPLOAD_OSS_GLB_DIRECTORY = join(PROJECT_ROOT, "upload_oss_glb");
const MAX_SKETCHFAB_FILE_SIZE_BYTES = 25 * 1024 * 1024;
const UPLOAD_OSS_GLB_ASSETS_MODULE_PATH = join(
    PROJECT_ROOT,
    "src/pages/planeRender/uploadOssGlbAssets.generated.ts",
);

// 递归查找 sketchfab 目录下超过大小限制的普通文件，符号链接不跟随以避免越出项目目录。
const findOversizedSketchfabFiles = async (directoryPath: string): Promise<string[]> => {
    const entries = await readdir(directoryPath, { withFileTypes: true });
    const oversizedFiles: string[] = [];

    for (const entry of entries) {
        const entryPath = join(directoryPath, entry.name);

        if (entry.isSymbolicLink()) {
            continue;
        }

        if (entry.isDirectory()) {
            oversizedFiles.push(...(await findOversizedSketchfabFiles(entryPath)));
            continue;
        }

        if (!entry.isFile()) {
            continue;
        }

        const fileStats = await stat(entryPath);

        if (fileStats.size > MAX_SKETCHFAB_FILE_SIZE_BYTES) {
            oversizedFiles.push(entryPath);
        }
    }

    return oversizedFiles;
};

// 递归查找 upload_oss_glb 目录中的 GLB 文件，符号链接不跟随以避免越出项目目录。
const findUploadOssGlbFiles = async (directoryPath: string): Promise<string[]> => {
    const entries = await readdir(directoryPath, { withFileTypes: true });
    const uploadFiles: string[] = [];

    for (const entry of entries) {
        const entryPath = join(directoryPath, entry.name);

        if (entry.isSymbolicLink()) {
            continue;
        }

        if (entry.isDirectory()) {
            uploadFiles.push(...(await findUploadOssGlbFiles(entryPath)));
            continue;
        }

        if (entry.isFile() && entry.name.toLowerCase().endsWith(".glb")) {
            uploadFiles.push(entryPath);
        }
    }

    return uploadFiles;
};

// 写入构建期 upload_oss_glb 清单，页面端据此生成 OSS 资源与加载地址。
const writeUploadOssGlbAssetsModule = async (filePaths: string[]): Promise<void> => {
    const assetEntries = filePaths
        .map((filePath: string): string => {
            const relativeUploadFilePath = relative(UPLOAD_OSS_GLB_DIRECTORY, filePath)
                .split(sep)
                .join("/");
            const sourcePath = `sketchfab/${relativeUploadFilePath}`;
            const fileName = relativeUploadFilePath.split("/").pop() ?? relativeUploadFilePath;

            return `    { sourcePath: ${JSON.stringify(sourcePath)}, fileName: ${JSON.stringify(fileName)} },`;
        })
        .join("\n");
    const assetEntriesRecord = assetEntries
        ? `[
${assetEntries}
]`
        : "[]";
    const moduleSource = [
        "// This file is generated by pluginSketchfabFileSizeGuard during the production build.",
        "// Do not edit by hand.",
        `export const uploadOssGlbAssets = ${assetEntriesRecord} as const;`,
        "",
    ].join("\n");

    await writeFile(UPLOAD_OSS_GLB_ASSETS_MODULE_PATH, moduleSource, "utf8");
};

// 读取并移动所有超限模型，再生成 upload_oss_glb 清单供页面端使用。
const moveOversizedSketchfabFiles = async (): Promise<void> => {
    let oversizedFiles: string[];

    try {
        oversizedFiles = await findOversizedSketchfabFiles(SKETCHFAB_DIRECTORY);
    } catch (error: unknown) {
        if (error instanceof Error && "code" in error && error.code === "ENOENT") {
            console.info("[sketchfab-size-guard] 未找到 sketchfab 目录，跳过检查。");
            oversizedFiles = [];
        } else {
            const reason = error instanceof Error ? error.message : String(error);
            throw new Error(`[sketchfab-size-guard] 扫描 sketchfab 目录失败：${reason}`);
        }
    }

    const currentMovedFilePaths: string[] = [];

    for (const filePath of oversizedFiles) {
        const relativeFilePath = relative(PROJECT_ROOT, filePath).split(sep).join("/");
        const relativeSketchfabFilePath = relative(SKETCHFAB_DIRECTORY, filePath);
        const uploadFilePath = join(UPLOAD_OSS_GLB_DIRECTORY, relativeSketchfabFilePath);

        await mkdir(dirname(uploadFilePath), { recursive: true });
        await rename(filePath, uploadFilePath);
        currentMovedFilePaths.push(relativeFilePath);
        console.warn(
            `[sketchfab-size-guard] 已移动超过 25 MiB 的文件：${relativeFilePath} -> ${relative(uploadFilePath, UPLOAD_OSS_GLB_DIRECTORY).split(sep).join("/")}`,
        );
    }

    let uploadOssGlbFiles: string[];

    try {
        uploadOssGlbFiles = await findUploadOssGlbFiles(UPLOAD_OSS_GLB_DIRECTORY);
    } catch (error: unknown) {
        if (error instanceof Error && "code" in error && error.code === "ENOENT") {
            uploadOssGlbFiles = [];
        } else {
            const reason = error instanceof Error ? error.message : String(error);
            throw new Error(`[sketchfab-size-guard] 扫描 upload_oss_glb 目录失败：${reason}`);
        }
    }

    await writeUploadOssGlbAssetsModule(uploadOssGlbFiles.sort());

    if (currentMovedFilePaths.length === 0) {
        console.info("[sketchfab-size-guard] 本次未发现超过 25 MiB 的文件。");
    }
};

// 在生产构建开始前移出超大 Sketchfab 模型，避免它们参与资源处理和最终产物生成。
export const pluginSketchfabFileSizeGuard = (): RsbuildPlugin => ({
    name: "plugin-sketchfab-file-size-guard",
    setup(api): void {
        api.onBeforeBuild(async (): Promise<void> => {
            await moveOversizedSketchfabFiles();
        });
    },
});
