import { mkdir, readFile, readdir, rename, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import type { RsbuildPlugin } from "@rsbuild/core";

const PLUGIN_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(PLUGIN_DIRECTORY, "..");
const SKETCHFAB_DIRECTORY = join(PROJECT_ROOT, "sketchfab");
const UPLOAD_OSS_GLB_DIRECTORY = join(PROJECT_ROOT, "upload_oss_glb");
const MAX_SKETCHFAB_FILE_SIZE_BYTES = 25 * 1024 * 1024;
const DELETED_SKETCHFAB_ASSETS_MODULE_PATH = join(
    PROJECT_ROOT,
    "src/pages/planeRender/deletedSketchfabAssets.generated.ts",
);

// 读取历史超限记录，保证本地文件移出后后续构建仍能使用对应的 OSS 兜底资源。
const readDeletedSketchfabAssetPaths = async (): Promise<string[]> => {
    try {
        const moduleSource = await readFile(DELETED_SKETCHFAB_ASSETS_MODULE_PATH, "utf8");
        const pathMatches = moduleSource.matchAll(/^\s*"(sketchfab\/[^"]+)": true,/gm);

        return Array.from(
            new Set(Array.from(pathMatches, (pathMatch: RegExpMatchArray): string => pathMatch[1])),
        );
    } catch (error: unknown) {
        if (error instanceof Error && "code" in error && error.code === "ENOENT") {
            return [];
        }

        const reason = error instanceof Error ? error.message : String(error);
        throw new Error(`[sketchfab-size-guard] 读取删除记录失败：${reason}`);
    }
};

// 仅保留当前文件系统中仍不存在的历史路径；文件恢复后不再被误判为已移出资源。
const retainMissingDeletedSketchfabAssetPaths = async (
    deletedFilePaths: string[],
): Promise<string[]> => {
    const missingFilePaths: string[] = [];

    for (const relativeFilePath of deletedFilePaths) {
        try {
            await stat(join(PROJECT_ROOT, relativeFilePath));
        } catch (error: unknown) {
            if (error instanceof Error && "code" in error && error.code === "ENOENT") {
                missingFilePaths.push(relativeFilePath);
                continue;
            }

            const reason = error instanceof Error ? error.message : String(error);
            throw new Error(`[sketchfab-size-guard] 检查历史删除记录失败：${reason}`);
        }
    }

    return missingFilePaths;
};

// 递归查找 sketchfab 目录下超过大小限制的普通文件，符号链接不跟随以避免越出项目目录。
const findOversizedSketchfabFiles = async (directoryPath: string): Promise<string[]> => {
    const entries = await readdir(directoryPath, { withFileTypes: true });
    const oversizedFiles: string[] = [];

    for (const entry of entries) {
        const entryPath = join(directoryPath, entry.name);

        if (entry.isSymbolicLink()) {
            continue;
        }

        if (entry.isDirectory()) {
            oversizedFiles.push(...(await findOversizedSketchfabFiles(entryPath)));
            continue;
        }

        if (!entry.isFile()) {
            continue;
        }

        const fileStats = await stat(entryPath);

        if (fileStats.size > MAX_SKETCHFAB_FILE_SIZE_BYTES) {
            oversizedFiles.push(entryPath);
        }
    }

    return oversizedFiles;
};

// 写入当前仍被移出的路径，供页面端只替换这些模型的 OSS 地址。
const writeDeletedSketchfabAssetsModule = async (deletedFilePaths: string[]): Promise<void> => {
    const deletedFileEntries = deletedFilePaths
        .map((filePath: string): string => `    ${JSON.stringify(filePath)}: true,`)
        .join("\n");
    const deletedFilePathsRecord = deletedFileEntries
        ? `{
${deletedFileEntries}
}`
        : "{}";
    const moduleSource = [
        "// This file is generated by pluginSketchfabFileSizeGuard during production build.",
        "// Do not edit by hand.",
        `export const deletedSketchfabAssetPaths = ${deletedFilePathsRecord} as const satisfies Record<string, true>;`,
        "",
    ].join("\n");

    await writeFile(DELETED_SKETCHFAB_ASSETS_MODULE_PATH, moduleSource, "utf8");
};

// 读取并移动所有超限模型，同时返回本次实际移出的项目相对路径。
const moveOversizedSketchfabFiles = async (): Promise<string[]> => {
    let oversizedFiles: string[];
    const previousDeletedFilePaths = await readDeletedSketchfabAssetPaths();

    try {
        oversizedFiles = await findOversizedSketchfabFiles(SKETCHFAB_DIRECTORY);
    } catch (error: unknown) {
        if (error instanceof Error && "code" in error && error.code === "ENOENT") {
            console.info("[sketchfab-size-guard] 未找到 sketchfab 目录，跳过检查。");
            const missingDeletedFilePaths = await retainMissingDeletedSketchfabAssetPaths(
                previousDeletedFilePaths,
            );
            await writeDeletedSketchfabAssetsModule(missingDeletedFilePaths);
            return missingDeletedFilePaths;
        }

        const reason = error instanceof Error ? error.message : String(error);
        throw new Error(`[sketchfab-size-guard] 扫描 sketchfab 目录失败：${reason}`);
    }

    const currentDeletedFilePaths: string[] = [];

    for (const filePath of oversizedFiles) {
        const relativeFilePath = relative(PROJECT_ROOT, filePath).split(sep).join("/");
        const relativeSketchfabFilePath = relative(SKETCHFAB_DIRECTORY, filePath);
        const uploadFilePath = join(UPLOAD_OSS_GLB_DIRECTORY, relativeSketchfabFilePath);

        await mkdir(dirname(uploadFilePath), { recursive: true });
        await rename(filePath, uploadFilePath);
        currentDeletedFilePaths.push(relativeFilePath);
        console.warn(
            `[sketchfab-size-guard] 已移动超过 25 MiB 的文件：${relativeFilePath} -> ${relative(uploadFilePath, UPLOAD_OSS_GLB_DIRECTORY).split(sep).join("/")}`,
        );
    }

    const missingPreviousDeletedFilePaths = await retainMissingDeletedSketchfabAssetPaths(
        previousDeletedFilePaths,
    );
    const deletedFilePaths = Array.from(
        new Set([...missingPreviousDeletedFilePaths, ...currentDeletedFilePaths]),
    ).sort();

    await writeDeletedSketchfabAssetsModule(deletedFilePaths);

    if (currentDeletedFilePaths.length === 0) {
        console.info("[sketchfab-size-guard] 本次未发现超过 25 MiB 的文件。");
    }

    return deletedFilePaths;
};

// 在生产构建开始前移出超大 Sketchfab 模型，避免它们参与资源处理和最终产物生成。
export const pluginSketchfabFileSizeGuard = (): RsbuildPlugin => ({
    name: "plugin-sketchfab-file-size-guard",
    setup(api): void {
        api.onBeforeBuild(async (): Promise<void> => {
            await moveOversizedSketchfabFiles();
        });
    },
});
