// This file is generated by pluginAircraftPhotoPreviews during production build.
// Preview cache version: 600w-jpeg-q82-v3
// Do not edit by hand.
export const aircraftPhotoPreviewUrls = {

} satisfies Record<string, string>;

export const aircraftPhotoPreviewFailures = {

} satisfies Record<string, number>;
