// This file is generated by pluginAircraftPhotoPreviews during production build.
// Preview cache version: 480p-v1
// Do not edit by hand.
export const aircraftPhotoPreviewUrls = {

} satisfies Record<string, string>;
